apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cicd
resources:
  - namespace.yaml
  - github-pipelines-credentials.yaml
  - quay-pipelines-credentials.yaml
  - pipelines
  
