apiVersion: v1
data:
  .dockerconfigjson: <quay credentials>
kind: Secret
metadata:
  annotations:
    tekton.dev/docker-0: https://quay.io
  name: quay-pipelines-credentials
  namespace: cicd
type: kubernetes.io/dockerconfigjson
