apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: java-pr-build
  namespace: cicd
spec:
  params:
  - default: https://github.com/redhat-telco-adoption/quarkus-demo.git
    name: git-repo-url
    type: string
  - default: quay.io/redhat-telco-adoption/quarkus-demo
    name: container-image
    type: string
  - name: git-sha
    type: string
  - name: git-pr-number
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.git-repo-url)
    - name: revision
      value: $(params.git-sha)
    - name: refspec
      value: ""
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: crtFileName
      value: ca-bundle.crt
    - name: subdirectory
      value: ""
    - name: sparseCheckoutDirectories
      value: ""
    - name: deleteExisting
      value: "true"
    - name: httpProxy
      value: ""
    - name: httpsProxy
      value: ""
    - name: noProxy
      value: ""
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:16b8e98aa03a874dfc0fd16cd4aaaeea193dc60882c61653e768f8f503fe33e3
    - name: userHome
      value: /home/git
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: workspace
  - name: maven
    params:
    - name: MAVEN_IMAGE
      value: registry.redhat.io/ubi8/openjdk-17@sha256:7942acf43a41b8fd202de7c5f7745d9732fae00a401b3da06e1ac988ac26ba4d
    - name: GOALS
      value:
      - --batch-mode
      - package
    - name: MAVEN_MIRROR_URL
      value: ""
    - name: SERVER_USER
      value: ""
    - name: SERVER_PASSWORD
      value: ""
    - name: PROXY_USER
      value: ""
    - name: PROXY_PASSWORD
      value: ""
    - name: PROXY_PORT
      value: ""
    - name: PROXY_HOST
      value: ""
    - name: PROXY_NON_PROXY_HOSTS
      value: ""
    - name: PROXY_PROTOCOL
      value: http
    - name: CONTEXT_DIR
      value: .
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: maven
    workspaces:
    - name: source
      workspace: workspace
    - name: maven-settings
      workspace: maven-settings
  - name: buildah
    params:
    - name: IMAGE
      value: $(params.container-image)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:bafb452c5346d8517d94639efa90e8d6d72cd11e45d49369c3d9305784d1c3f6
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: ./src/main/docker/Dockerfile.jvm
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: BUILD_EXTRA_ARGS
      value: ""
    - name: PUSH_EXTRA_ARGS
      value: ""
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - maven
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: workspace
  - name: provision-preview-environment
    params:
    - name: PR_NUMBER
      value: $(params.git-pr-number)
    - name: NEW_IMAGE_TAG
      value: $(params.container-image)
    - name: REPO_URL
      value: https://github.com/redhat-telco-adoption/quarkus-demo-config.git
    runAfter:
    - buildah
    taskRef:
      kind: Task
      name: provision-preview-environment
    workspaces:
    - name: workspace
      workspace: workspace
  workspaces:
  - name: workspace
  - name: maven-settings
