apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: java-release
  name: el-java-release
spec:
  tls:
    termination: edge
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-java-release
    weight: null
status: {}
