apiVersion: triggers.tekton.dev/v1beta1
kind: ClusterTriggerBinding
metadata:
  labels:
    operator.tekton.dev/operand-name: openshift-pipelines-addons
  name: github-tag-created
spec:
  params:
  - name: git-repo-url
    value: $(body.repository.html_url)
  - name: git-repo-name
    value: $(body.repository.full_name)
  - name: content-type
    value: $(header.Content-Type)
  - name: git-ref
    value: $(body.ref)
  - name: git-ref-type
    value: $(body.ref_type)
  - name: git-branch
    value: $(body.master_branch)
