apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: java-pr-close
  namespace: cicd
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - kind: ClusterTriggerBinding
      ref: github-pullreq
    interceptors:
    - params:
      - name: eventTypes
        value:
        - pull_request
      ref:
        apiVersion: triggers.tekton.dev
        kind: ClusterInterceptor
        name: github
    - name: Only when PRs are closed
      params:
      - name: filter
        value: has(body.action) && body.action in ['closed']
      ref:
        kind: ClusterInterceptor
        name: cel
    template:
      ref: java-pr-close
