apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: quarkus-demo
  namespace: openshift-gitops
spec:
  generators:
  - git:
      repoURL: https://github.com/redhat-telco-adoption/quarkus-demo-config
      revision: main
      directories:
      - path: overlays/*
      - path: overlays/preview-environments/*
      - path: overlays/preview-environments/template
        exclude: true
      
  template:
    metadata:
      name: '{{path.basename}}'
    spec:
      project: default
      syncPolicy:
        #preserveResourcesOnDeletion: false
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 15
          backoff:
            duration: 15s
            factor: 2
            maxDuration: 5m
      source:
        repoURL: https://github.com/redhat-telco-adoption/quarkus-demo-config
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'